### ISSUE TITLE
Add token(s) for text-decoration/underline

### ISSUE THREAD

**Issue by mcoker** [patternfly/design-tokens#40]
We are underlining some things in penta, and should add some tokens for that. Primarily what we're setting is:

* Style - eg, solid (regular underline) or dashed (for use with help text that triggers a popover/tooltip)
* Width
* Color
* Offset - how far it is from the text

cc @lboehling

**Comment by lboehling** [comment]
Hey @mcoker! i added text decoration tokens in [this figma branch](https://www.figma.com/design/iPks6qJfvvwGOTHgpoIvHm/branch/WjSzT6AB2jYkDOeLM64rDn/PatternFly-6%3A-Design-Tokens-%26-Styles?m=auto&node-id=83-132&t=6fCTY5JRyvYlRW1w-1)

Here is a quick overview of the tokens I added: 

**Base Tokens**

<img width="408" alt="Screenshot 2024-06-06 at 1 58 58 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/20e1aa65-17bf-4816-a0ce-ccb68fcc0112">


**Semantic Tokens**

_Width/Offset tokens_
<img width="421" alt="Screenshot 2024-06-06 at 1 58 08 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/f55eaa1c-bfaf-4937-bdec-1024f3474ea0">

_Help text tokens_
<img width="407" alt="Screenshot 2024-06-06 at 1 58 40 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/76e8e217-1c3a-4e14-8dd1-bece23a2f73d">

_Link tokens_
<img width="407" alt="Screenshot 2024-06-06 at 1 58 28 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/62713586-8abe-4d74-a111-1c63aac16549">

_Editable text tokens_
<img width="412" alt="Screenshot 2024-06-06 at 1 58 22 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/ddd488b7-c451-4be7-aaa1-f6b98f551156">


I didn't add specific tokens for color because I think we previously discussed the underlines inheriting the text color. I can add specific color tokens, too, if you feel we need them!

**Comment by lboehling** [comment]
hey @mcoker if these look alright, i can merge this branch before I'm out!

**Comment by mcoker** [comment]
@lboehling these lgtm. One change is `--line--200: underlined` should just be `underline` (present tense).

re: colors, I'd say if you want that to be a themable part of PF, we can add them. Otherwise we can add later if the use case comes up 👍

**Comment by lboehling** [comment]
i think we can add the colors later if the use case comes up! these tokens are in figma now :)
