### ISSUE TITLE
Tokens: Severity icon color tokens

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/design-tokens#42]
```[tasklist]
### Tasks
- [ ] Unidentified
- [ ] None
- [ ] Minor
- [ ] Moderate
- [ ] Important
- [ ] Critical
```
<img width="539" alt="Screenshot 2024-05-02 at 11 24 27 AM" src="https://github.com/patternfly/design-tokens/assets/28658548/acd86f64-1be2-40ef-ac58-1978f1ec9e7e">

**Comment by lboehling** [comment]
added tokens to  support for severity icon colors.

I set up the naming of these tokens to be consistent with the naming of our other status/non status icon colors. I didn't add hover/clicked tokens since I don't think they're needed now, but the naming is set up so that they can be added easily if we do need them. 


**Semantic color tokens added**
<img width="616" alt="Screenshot 2024-05-02 at 3 03 05 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/7b9b1a97-e549-4db5-a34e-3a8e88fe276d">


**Base dark color tokens added**
<img width="439" alt="Screenshot 2024-05-02 at 3 02 50 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/9499f180-8bf0-4aa7-bbc2-66c7dae5253e">

**Base light color tokens added**
<img width="429" alt="Screenshot 2024-05-02 at 3 02 41 PM" src="https://github.com/patternfly/design-tokens/assets/46571616/aca207db-79d8-4b84-b276-73c7e6edb4ce">

**Comment by andrew-ronaldson** [comment]
Thanks for getting these into the library!
